"""Add indexes to foreign keys

Revision ID: 192f838d2476
Revises: 1313753c012c
Create Date: 2025-12-06 20:50:51.381549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192f838d2476'
down_revision: Union[str, Sequence[str], None] = '1313753c012c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_logs_run_id'), 'logs', ['run_id'], unique=False)
    op.create_index(op.f('ix_optimizations_task_id'), 'optimizations', ['task_id'], unique=False)
    op.create_index(op.f('ix_runs_task_id'), 'runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_task_id'), table_name='runs')
    op.drop_index(op.f('ix_optimizations_task_id'), table_name='optimizations')
    op.drop_index(op.f('ix_logs_run_id'), table_name='logs')
    # ### end Alembic commands ###
